name: Build and Deploy React App to Azure - flight-sim

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Show directory contents
        run: ls -R

      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: build  # Upload the actual production files

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: ./build-folder

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'flight-sim'  # use your actual App Service name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_709BF6DB78BF45F2AA54C5325F292528 }}
          package: ./build-folder/build  # deploy the downloaded folder
